name: DimensionalBlocks
main: com.aaaaahhhhhhh.bananapuncher714.dimensional.block.library.DimensionalBlocks
version: 1.1.3
description: Add custom blocks to Spigot
author: BananaPuncher714
api-version: 1.13
load: STARTUP
commands:
  dimensionalblocks:
    description: "Dump blockstates"